import {
  AlertTriangle,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  Command,
  File,
  FileText,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  Plus,
  Trash,
  User,
  User2Icon,
  X,
  ListTree,
  ListTodo,
  SlidersHorizontalIcon,
  LogOut,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  event: ListTree,
  submittedEvent: ListTodo,
  setting: SlidersHorizontalIcon,
  logout: LogOut,
};
